### ISSUE TITLE
第9回 :sushi: 総集編

### ISSUE THREAD

**Issue by yudai-ez** [yudai-ez/dokusyokai#8]
今までの内容を振り返り、議論中心の回とする

**Comment by myamaguchi-ts** [comment]
:sushi:

**Comment by yudai-ez** [comment]
インセプションデッキをつくってみるのはどうだろう

**Comment by yudai-ez** [comment]
- 野坂さん: シーン7がよくわからなかったのでおさらいしたい
  - スプリントのおさらい
  - スプリント計画ミーティングのおさらい
  - プロダクトバックログのおさらい

- 伊東さん: タスクボードのようなものはどのようなものが使いやすかったか？yudaiの経験の中で意見があれば教えてほしい
  - yudai: 個人的にはtrelloとかredmineとかzenhubのようなものよりも、アナログなホワイトボード + 付箋の方がやりやすかった
  - 著者のryuzeeさんも同意見だった
  - しかし、リモートで作業することもあるので、プロジェクトの状況にうまく合わせる必要もある
  - redmineとかjiraは、機能が多すぎるので本来の目的と異なることにつかわれたり、管理コストがかかるデメリットがある

**Comment by yudai-ez** [comment]
yudai [3:13 PM] 
第一部

プロダクトオーナーは何がほしいのか
開発チームはどれくらいできそうか
第二部

開発チームはどうやってそれを実現するか

qurage [3:13 PM] 
ハイ

[3:14] 
行くんで

qurage [3:32 PM] 
実用最小限の製品 -Minimum Viable Product かな

[3:32] 
初めて知った用語だ
2  

inoue_y [3:35 PM] 
Viable とは

[3:35] 
=> 実行可能な

qurage [3:36 PM] 
なるほど
​*viable*​
【形】
〔計画などが〕実行可能な
〔胎児・新生児などが〕生きていける、生存能力のある
〔動物・植物などが〕成長できる
〔国などが〕発展しうる、存続能力のある

[3:37] 
これ発音 う゛ぁいあぼー か

nakamura_kaz [3:44 PM] 
http://www.find-job.net/startup/20-intro-movies

yudai [3:49 PM] 
uruさんはタスク管理が下手という話題でもりあがってる

[3:51] 
https://ja.wikipedia.org/wiki/YAGNI

ito [3:55 PM] 
犠牲的アーキテクチャ

yudai [3:56 PM] 
http://forza.cocolog-nifty.com/blog/2014/12/post-2649.html


inoue_y [3:56 PM] 
別名: 式年遷宮アーキテクチャ

qurage [3:59 PM] 
犠牲的アーキテクチャ (Sacrificial Architecture)

inoue_y [4:04 PM] 
まとめ(?): システム開発は家造り

qurage [4:07 PM] 
家造りの例えの場合、建築と開発では技術的手法の変化速度という点でかなりの差があるので、たとえ話を進めていくとその部分だけずれることありますね(edited)

[4:08] 
建築だったら工期もっと厳密にできるというイメージを持たれることもあるのかもしれない

qurage [4:17 PM] 
家つながりでしかない全く関係ないはなしだけど、
理屈 vs 感情という話になったとき、理屈が家で、感情は食べ物だと考えると迷わないで済むこと多い気がしてて、よくそんなこと考える
